INSERT INTO MAP_GAME(ID, MAP_BODY, NAME, USED, DELETED) VALUES  (1, '0,1,0,1,0;1,0,0,0,0;0,0,0,1,0;0,1,0,0,0', 'Paris', false, false);
INSERT INTO MAP_GAME(ID, MAP_BODY, NAME, USED, DELETED) VALUES  (2, '0,0,1,1,0;0,1,0,1,0;0,1,0,1,0;0,0,1,1,0', 'Moscow', false, false);
INSERT INTO MAP_GAME(ID, MAP_BODY, NAME, USED, DELETED) VALUES  (3, '0,1,0,0,0;0,1,0,1,0;0,1,0,1,0;0,1,0,1,0', 'Berlin', true, false);
INSERT INTO MAP_GAME(ID, MAP_BODY, NAME, USED, DELETED) VALUES  (4, '0,1,0,1,0;0,0,1,1,0;0,0,0,1,0;0,0,0,1,0', 'Warsaw', false, false);

-- INSERT INTO CAR(NAME, TYPE, IS_CRASHED, MAP_NAME) VALUES  ('BMW', 'NORMAL', false, 'Warsaw');
-- INSERT INTO CAR(NAME, TYPE, IS_CRASHED, MAP_NAME) VALUES  ('Mercedes', 'RACING', false, 'Warsaw');
-- INSERT INTO CAR(NAME, TYPE, IS_CRASHED, MAP_NAME) VALUES  ('Honda', 'RACING', false, 'Paris');

-- INSERT INTO CAR_HISTORY(MOVE, NAME, TYPE) VALUES  ('FORWARD', 'BMW', 'NORMAL');
-- INSERT INTO CAR_HISTORY(MOVE, NAME, TYPE) VALUES  ('FORWARD', 'BMW', 'NORMAL');
-- INSERT INTO CAR_HISTORY(MOVE, NAME, TYPE) VALUES  ('TURN_RIGHT', 'BMW', 'NORMAL');
-- INSERT INTO CAR_HISTORY(MOVE, NAME, TYPE) VALUES  ('TURN_LEFT', 'BMW', 'NORMAL');
-- INSERT INTO CAR_HISTORY(MOVE, NAME, TYPE) VALUES  ('FORWARD', 'BMW', 'NORMAL');
